// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Y-CEAs16xO7iIbdXQDYtwQWZtfCvYKc',
    appId: '1:795032449652:web:90fe902ed0bea28c691721',
    messagingSenderId: '795032449652',
    projectId: 'fir-projesi-e8e23',
    authDomain: 'fir-projesi-e8e23.firebaseapp.com',
    storageBucket: 'fir-projesi-e8e23.appspot.com',
    measurementId: 'G-49B052TTZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg4J5IimyiGTbcA-8TwKPEucPb_rqbmVM',
    appId: '1:795032449652:android:808ed1f5489d9d65691721',
    messagingSenderId: '795032449652',
    projectId: 'fir-projesi-e8e23',
    storageBucket: 'fir-projesi-e8e23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3IaUNGw4rkkUL0rdddUO4cmSEOC4Jrnk',
    appId: '1:795032449652:ios:809762f9eadde364691721',
    messagingSenderId: '795032449652',
    projectId: 'fir-projesi-e8e23',
    storageBucket: 'fir-projesi-e8e23.appspot.com',
    iosBundleId: 'com.example.firebaseDeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3IaUNGw4rkkUL0rdddUO4cmSEOC4Jrnk',
    appId: '1:795032449652:ios:a5767d7ca1033ac3691721',
    messagingSenderId: '795032449652',
    projectId: 'fir-projesi-e8e23',
    storageBucket: 'fir-projesi-e8e23.appspot.com',
    iosBundleId: 'com.example.firebaseDeneme.RunnerTests',
  );
}
